#!/usr/bin/env ts-node
/**
 * Adapt Claude Code skills for API invocation
 *
 * This script reads SKILL.md files and creates api-prompt.md versions
 * that are suitable for backend API invocation via Claude API (Bedrock or direct).
 *
 * Changes made:
 * - Removes tool-specific instructions (Read, Write, Bash, etc.)
 * - Removes file I/O operations
 * - Focuses on reasoning and structured output
 * - Adds JSON/XML output format requirements
 */

import * as fs from 'fs/promises';
import * as path from 'path';

interface SkillConfig {
  name: string;
  inputPath: string;
  outputPath: string;
}

const API_SKILLS: SkillConfig[] = [
  {
    name: 'epic-feature-creator',
    inputPath: '../api-skills/epic-feature-creator/SKILL.md',
    outputPath: '../api-skills/epic-feature-creator/api-prompt.md',
  },
  {
    name: 'feature-story-creator',
    inputPath: '../api-skills/feature-story-creator/SKILL.md',
    outputPath: '../api-skills/feature-story-creator/api-prompt.md',
  },
];

/**
 * Sections to remove from API version
 */
const SECTIONS_TO_REMOVE = [
  /## Tool Usage.*/s,
  /## File Operations.*/s,
  /## Reading Files.*/s,
  /## Writing Files.*/s,
  /## Bash Commands.*/s,
  /Use the Read tool.*/gi,
  /Use the Write tool.*/gi,
  /Use the Bash tool.*/gi,
  /Use the Edit tool.*/gi,
  /Use the Glob tool.*/gi,
  /Use the Grep tool.*/gi,
];

/**
 * Add API-specific instructions
 */
const API_INSTRUCTIONS = `

## Output Format

**IMPORTANT:** Your response will be parsed programmatically. You MUST return a valid JSON object with the following structure:

\`\`\`json
{
  "items": [
    {
      "title": "Item title",
      "description": "Detailed description",
      "acceptanceCriteria": ["Criteria 1", "Criteria 2"],
      "technicalNotes": "Optional technical notes",
      "estimatedComplexity": "low|medium|high"
    }
  ],
  "metadata": {
    "totalItems": 3,
    "generatedAt": "ISO timestamp",
    "modelUsed": "model-id"
  }
}
\`\`\`

Do NOT include any text before or after the JSON object.
Do NOT use markdown code blocks around the JSON.
Ensure the JSON is valid and properly escaped.

`;

async function adaptSkill(config: SkillConfig): Promise<void> {
  const scriptDir = __dirname;
  const inputPath = path.resolve(scriptDir, config.inputPath);
  const outputPath = path.resolve(scriptDir, config.outputPath);

  console.log(`\n📝 Processing: ${config.name}`);
  console.log(`   Input:  ${inputPath}`);
  console.log(`   Output: ${outputPath}`);

  try {
    // Read original skill
    let content = await fs.readFile(inputPath, 'utf-8');

    // Remove tool-specific sections
    console.log('   🔧 Removing tool-specific instructions...');
    for (const pattern of SECTIONS_TO_REMOVE) {
      content = content.replace(pattern, '');
    }

    // Clean up multiple consecutive blank lines
    content = content.replace(/\n{3,}/g, '\n\n');

    // Add API-specific instructions
    console.log('   ✨ Adding API output format instructions...');
    content = content + API_INSTRUCTIONS;

    // Add header comment
    const header = `<!--
  API-adapted version of ${config.name}
  Generated by: adapt-for-api.ts
  Generated at: ${new Date().toISOString()}

  This version is optimized for backend API invocation via Claude API.
  - Tool-specific instructions removed
  - Structured JSON output required
  - Stateless, single-turn operation
-->

`;
    content = header + content;

    // Write API version
    await fs.writeFile(outputPath, content, 'utf-8');
    console.log(`   ✅ Created: ${outputPath}`);

  } catch (error) {
    console.error(`   ❌ Error processing ${config.name}:`, error);
    throw error;
  }
}

async function main() {
  console.log('🚀 APDevFlow Skill API Adapter');
  console.log('================================\n');

  for (const config of API_SKILLS) {
    await adaptSkill(config);
  }

  console.log('\n✨ All skills adapted successfully!\n');
  console.log('📦 API-ready prompts created:');
  for (const config of API_SKILLS) {
    console.log(`   - ${config.outputPath}`);
  }
  console.log('\n💡 These files can be loaded by Lambda functions for Bedrock API calls.\n');
}

// Run if called directly
if (require.main === module) {
  main().catch((error) => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
}

export { adaptSkill, API_SKILLS };
